color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.9176375488750637
  lightness: 0.1479789351578802
  saturation: 0.05198807502165437
  rhythmicContrast: 0.36081940261647105
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: krgoodri.ch
layout_spectrum: 0.7476936795283109
typography_spectrum: 0.8140759877860546
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F5l2EUDevI9s%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D5l2EUDevI9s&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F5l2EUDevI9s%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Cat Music
          url: 'https://www.youtube.com/user/catmusicoffice'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - voltaj
        - duration
        - cat
        - views
        - music
        - video
        - official
        - http
        - www
        - vama
      description: >-
        Voltaj - Lumea e a mea (Official Video) by Cat Music Buy the single from
        iTunes: http://tinyurl.com/voltaj-lumea-e-a-mea Playlist Voltaj:
        https://www.youtube.com/watch?v=u-mP0CLmlYY&list=PL4tPz0lSXLKFqAF34Z6Ar4ZZjRIdzXSjG&index=2
        Subscribe to CatMusic:
        http://www.youtube.com/subscription_center?add_user=catmusicoffice Cat
        Music is the main player in the Romanian music industry, representing
        some of the most influential and successful artists from Romania, for
        the past 20 years.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=5l2EUDevI9s&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=5l2EUDevI9s&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=5l2EUDevI9s&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=5l2EUDevI9s&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=5l2EUDevI9s&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=5l2EUDevI9s'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=5l2EUDevI9s
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=5l2EUDevI9s
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/5l2EUDevI9s'
      title: Voltaj - Lumea e a mea (Official Video)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: krgoodri.ch
description: This is probably not about anything.
purpose:
  - type: contact
    url: 'mailto:i.am@krgoodri.ch'
    label: Contact me
url: 'https://krgoodri.ch'
github: true
